#!/bin/bash

# nic_name="ens1f3"
# local_ip=80.48.5.51
# export HCCL_IF_IP=$local_ip
# export GLOO_SOCKET_IFNAME=$nic_name
# export TP_SOCKET_IFNAME=$nic_name
# export HCCL_SOCKET_IFNAME=$nic_name

export FORCE_BUILD=0
export PYTORCH_NPU_ALLOC_CONF=max_split_size_mb:128
export VLLM_ATTENTION_BACKEND="TORCH_SDPA"
export VLLM_USE_V1=1
export VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
export VLLM_ENGINE_ITERATION_TIMEOUT_S=100000000000
export VLLM_ASCEND_ENABLE_NZ=0

export RAY_DEBUG_POST_MORTEM=0

export HCCL_IF_BASE_PORT=50000
export HCCL_HOST_SOCKET_PORT_RANGE=60000-60050
export HCCL_NPU_SOCKET_PORT_RANGE=61000-61050
export HCCL_INTRA_ROCE_ENABLE=1
export HCCL_INTRA_PCIE_ENABLE=0
# export HCCL_IF_IP=80.48.5.51
export HCCL_SOCKET_FAMILY=AF_INET
export HCCL_BUFFSIZE=128
export HCCL_OP_EXPANSION_MODE=AIV

export TOKENIZERS_PARALLELISM=true
export VLLM_LOGGING_LEVEL=WARN
export HYDRA_FULL_ERROR=1
# test