#!/usr/bin/env bash
set -euo pipefail

setup_common_env() {
  local rllm_dir
  rllm_dir=$(python3 -c "import rllm, os; print(os.path.dirname(os.path.dirname(rllm.__file__)))")
  export PYTHONPATH="${PYTHONPATH:-}:${rllm_dir}"

  export FORCE_BUILD=${FORCE_BUILD:-0}
  export VLLM_USE_V1=${VLLM_USE_V1:-1}
  export VLLM_ATTENTION_BACKEND=${VLLM_ATTENTION_BACKEND:-TORCH_SDPA}
  export VLLM_ALLOW_LONG_MAX_MODEL_LEN=${VLLM_ALLOW_LONG_MAX_MODEL_LEN:-1}
  export VLLM_ENGINE_ITERATION_TIMEOUT_S=${VLLM_ENGINE_ITERATION_TIMEOUT_S:-100000000000}
  export VLLM_ASCEND_ENABLE_NZ=${VLLM_ASCEND_ENABLE_NZ:-0}

  export RAY_DEBUG_POST_MORTEM=${RAY_DEBUG_POST_MORTEM:-0}
  export PYTORCH_NPU_ALLOC_CONF=${PYTORCH_NPU_ALLOC_CONF:-max_split_size_mb:512}
  export TASK_QUEUE_ENABLE=${TASK_QUEUE_ENABLE:-2}

  export TOKENIZERS_PARALLELISM=${TOKENIZERS_PARALLELISM:-true}
  export VLLM_LOGGING_LEVEL=${VLLM_LOGGING_LEVEL:-WARN}
  export RAY_DEDUP_LOGS=${RAY_DEDUP_LOGS:-1}
  export HYDRA_FULL_ERROR=${HYDRA_FULL_ERROR:-1}

  export HCCL_EXEC_TIMEOUT=${HCCL_EXEC_TIMEOUT:-7200}
  export HCCL_EVENT_TIMEOUT=${HCCL_EVENT_TIMEOUT:-7200}
  export HCCL_CONNECT_TIMEOUT=${HCCL_CONNECT_TIMEOUT:-7200}
  export ACL_DEVICE_SYNC_TIMEOUT=${ACL_DEVICE_SYNC_TIMEOUT:-7200}
  export HCCL_ASYNC_ERROR_HANDLING=${HCCL_ASYNC_ERROR_HANDLING:-0}
  export P2P_HCCL_BUFFSIZE=${P2P_HCCL_BUFFSIZE:-30}
  export HCCL_BUFFSIZE=${HCCL_BUFFSIZE:-300}
  export HCCL_HOST_SOCKET_PORT_RANGE=${HCCL_HOST_SOCKET_PORT_RANGE:-60000-60050}
  export HCCL_NPU_SOCKET_PORT_RANGE=${HCCL_NPU_SOCKET_PORT_RANGE:-61000-61050}
  export HCCL_INTRA_ROCE_ENABLE=${HCCL_INTRA_ROCE_ENABLE:-1}

  export GLOO_SOCKET_TIMEOUT=${GLOO_SOCKET_TIMEOUT:-7200}
  export RAY_ENABLE_RECORD_ACTOR_TASK_LOGGING=1

  export VLLM_ALLOW_RUNTIME_LORA_UPDATING=true
}