"""
Analysis script for PASS@K evaluation results.

This script analyzes the SQLite database generated by eval_pass_at_k.py
and produces detailed statistics and visualizations.

Usage:
    python scripts/analyze_pass_at_k.py --db-path results/pass_at_k/interactions.db --output-dir results/pass_at_k/analysis
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sqlite3
from collections import defaultdict
from datetime import datetime
from typing import Any

import numpy as np

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("analyze_pass_at_k")


def load_database(db_path: str) -> dict[str, Any]:
    """Load all data from SQLite database."""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    cursor.execute("SELECT * FROM rollouts")
    columns = [desc[0] for desc in cursor.description]
    rollouts = [dict(zip(columns, row)) for row in cursor.fetchall()]
    
    cursor.execute("SELECT * FROM turns")
    columns = [desc[0] for desc in cursor.description]
    turns = [dict(zip(columns, row)) for row in cursor.fetchall()]
    
    cursor.execute("SELECT * FROM problem_stats")
    columns = [desc[0] for desc in cursor.description]
    problem_stats = [dict(zip(columns, row)) for row in cursor.fetchall()]
    
    conn.close()
    
    return {
        "rollouts": rollouts,
        "turns": turns,
        "problem_stats": problem_stats,
    }


def calculate_pass_at_k(n: int, c: int, k: int) -> float:
    """Calculate pass@k metric."""
    if n - k < 0:
        return 0.0
    return 1.0 - np.prod(1.0 - k / np.arange(n - c + 1, n + 1)) if n > c else 1.0


def analyze_by_problem(data: dict[str, Any]) -> dict[str, Any]:
    """Analyze results grouped by problem."""
    rollouts_by_problem = defaultdict(list)
    for r in data["rollouts"]:
        rollouts_by_problem[r["problem_id"]].append(r)
    
    analysis = {}
    for problem_id, rollouts in rollouts_by_problem.items():
        total = len(rollouts)
        passed = sum(1 for r in rollouts if r["final_correct"])
        compiled = sum(1 for r in rollouts if r["final_compiled"])
        
        speedups = [r["best_speedup"] for r in rollouts if r["best_speedup"] > 0]
        rewards = [r["total_reward"] for r in rollouts]
        
        analysis[problem_id] = {
            "total_rollouts": total,
            "passed": passed,
            "compiled": compiled,
            "pass_rate": passed / total if total > 0 else 0,
            "compile_rate": compiled / total if total > 0 else 0,
            "best_speedup": max(speedups) if speedups else 0,
            "avg_speedup": np.mean(speedups) if speedups else 0,
            "avg_reward": np.mean(rewards) if rewards else 0,
            "pass_at_1": calculate_pass_at_k(total, passed, 1),
            "pass_at_5": calculate_pass_at_k(total, passed, 5),
            "pass_at_10": calculate_pass_at_k(total, passed, 10),
        }
    
    return analysis


def analyze_by_turn(data: dict[str, Any]) -> dict[str, Any]:
    """Analyze results by turn number."""
    turns_data = data["turns"]
    
    turn_analysis = defaultdict(lambda: {
        "total": 0,
        "compiled": 0,
        "correct": 0,
        "speedups": [],
        "rewards": [],
    })
    
    for t in turns_data:
        turn_num = t["turn"]
        turn_analysis[turn_num]["total"] += 1
        if t["compiled"]:
            turn_analysis[turn_num]["compiled"] += 1
        if t["correctness"]:
            turn_analysis[turn_num]["correct"] += 1
        turn_analysis[turn_num]["speedups"].append(t["speedup"])
        turn_analysis[turn_num]["rewards"].append(t["reward"])
    
    result = {}
    for turn_num, stats in sorted(turn_analysis.items()):
        result[f"turn_{turn_num}"] = {
            "total": stats["total"],
            "compile_rate": stats["compiled"] / stats["total"] if stats["total"] > 0 else 0,
            "correct_rate": stats["correct"] / stats["total"] if stats["total"] > 0 else 0,
            "avg_speedup": np.mean([s for s in stats["speedups"] if s > 0]) if stats["speedups"] else 0,
            "avg_reward": np.mean(stats["rewards"]) if stats["rewards"] else 0,
        }
    
    return result


def analyze_speedup_distribution(data: dict[str, Any]) -> dict[str, Any]:
    """Analyze speedup distribution."""
    rollouts = data["rollouts"]
    speedups = [r["best_speedup"] for r in rollouts if r["best_speedup"] > 0]
    
    if not speedups:
        return {"error": "No speedup data available"}
    
    return {
        "count": len(speedups),
        "min": float(np.min(speedups)),
        "max": float(np.max(speedups)),
        "mean": float(np.mean(speedups)),
        "median": float(np.median(speedups)),
        "std": float(np.std(speedups)),
        "percentiles": {
            "p25": float(np.percentile(speedups, 25)),
            "p50": float(np.percentile(speedups, 50)),
            "p75": float(np.percentile(speedups, 75)),
            "p90": float(np.percentile(speedups, 90)),
            "p95": float(np.percentile(speedups, 95)),
        },
        "buckets": {
            "1.0x-1.2x": sum(1 for s in speedups if 1.0 <= s < 1.2),
            "1.2x-1.5x": sum(1 for s in speedups if 1.2 <= s < 1.5),
            "1.5x-2.0x": sum(1 for s in speedups if 1.5 <= s < 2.0),
            "2.0x-3.0x": sum(1 for s in speedups if 2.0 <= s < 3.0),
            "3.0x+": sum(1 for s in speedups if s >= 3.0),
        },
    }


def analyze_error_patterns(data: dict[str, Any]) -> dict[str, Any]:
    """Analyze common error patterns."""
    turns = data["turns"]
    errors = [t["error"] for t in turns if t["error"]]
    
    error_patterns = defaultdict(int)
    for error in errors:
        if not error:
            continue
        error_lower = error.lower()
        if "compilation" in error_lower or "compile" in error_lower:
            error_patterns["compilation_error"] += 1
        elif "correctness" in error_lower or "mismatch" in error_lower:
            error_patterns["correctness_error"] += 1
        elif "timeout" in error_lower:
            error_patterns["timeout"] += 1
        elif "shape" in error_lower or "dimension" in error_lower:
            error_patterns["shape_error"] += 1
        elif "cuda" in error_lower or "gpu" in error_lower:
            error_patterns["cuda_error"] += 1
        elif "memory" in error_lower:
            error_patterns["memory_error"] += 1
        else:
            error_patterns["other"] += 1
    
    return {
        "total_errors": len(errors),
        "patterns": dict(error_patterns),
    }


def generate_plots(data: dict[str, Any], output_dir: str):
    """Generate visualization plots."""
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    
    os.makedirs(output_dir, exist_ok=True)
    
    problem_analysis = analyze_by_problem(data)
    
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    
    ax = axes[0, 0]
    pass_rates = [p["pass_rate"] for p in problem_analysis.values()]
    ax.hist(pass_rates, bins=20, color='steelblue', alpha=0.7, edgecolor='black')
    ax.set_xlabel('Pass Rate')
    ax.set_ylabel('Number of Problems')
    ax.set_title('Distribution of Pass Rates by Problem')
    ax.grid(True, alpha=0.3)
    
    ax = axes[0, 1]
    compile_rates = [p["compile_rate"] for p in problem_analysis.values()]
    ax.hist(compile_rates, bins=20, color='coral', alpha=0.7, edgecolor='black')
    ax.set_xlabel('Compile Rate')
    ax.set_ylabel('Number of Problems')
    ax.set_title('Distribution of Compile Rates by Problem')
    ax.grid(True, alpha=0.3)
    
    ax = axes[0, 2]
    speedups = [p["best_speedup"] for p in problem_analysis.values() if p["best_speedup"] > 0]
    if speedups:
        ax.hist(speedups, bins=20, color='green', alpha=0.7, edgecolor='black')
        ax.axvline(x=1.0, color='red', linestyle='--', linewidth=2, label='Baseline (1.0x)')
        ax.set_xlabel('Best Speedup')
        ax.set_ylabel('Number of Problems')
        ax.set_title('Distribution of Best Speedups')
        ax.legend()
    ax.grid(True, alpha=0.3)
    
    ax = axes[1, 0]
    turn_analysis = analyze_by_turn(data)
    if turn_analysis:
        turns = sorted([int(k.replace("turn_", "")) for k in turn_analysis.keys()])
        correct_rates = [turn_analysis[f"turn_{t}"]["correct_rate"] for t in turns]
        compile_rates = [turn_analysis[f"turn_{t}"]["compile_rate"] for t in turns]
        x = np.arange(len(turns))
        width = 0.35
        ax.bar(x - width/2, compile_rates, width, label='Compile Rate', color='coral')
        ax.bar(x + width/2, correct_rates, width, label='Correct Rate', color='green')
        ax.set_xlabel('Turn Number')
        ax.set_ylabel('Rate')
        ax.set_title('Compile and Correct Rates by Turn')
        ax.set_xticks(x)
        ax.set_xticklabels([f'Turn {t}' for t in turns])
        ax.legend()
    ax.grid(True, alpha=0.3)
    
    ax = axes[1, 1]
    rewards = [p["avg_reward"] for p in problem_analysis.values()]
    ax.hist(rewards, bins=20, color='purple', alpha=0.7, edgecolor='black')
    ax.set_xlabel('Average Reward')
    ax.set_ylabel('Number of Problems')
    ax.set_title('Distribution of Average Rewards')
    ax.grid(True, alpha=0.3)
    
    ax = axes[1, 2]
    speedup_dist = analyze_speedup_distribution(data)
    if "buckets" in speedup_dist:
        buckets = speedup_dist["buckets"]
        labels = list(buckets.keys())
        values = list(buckets.values())
        colors = ['#ff9999', '#ffcc99', '#ffff99', '#99ff99', '#99ccff']
        ax.pie(values, labels=labels, autopct='%1.1f%%', colors=colors[:len(labels)])
        ax.set_title('Speedup Distribution by Buckets')
    
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'analysis_overview.png'), dpi=150)
    plt.close()
    
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    
    ax = axes[0]
    sorted_problems = sorted(problem_analysis.items(), key=lambda x: x[1]["pass_rate"], reverse=True)[:20]
    problem_ids = [p[0][:25] for p in sorted_problems]
    pass_rates = [p[1]["pass_rate"] for p in sorted_problems]
    ax.barh(range(len(problem_ids)), pass_rates, color='steelblue')
    ax.set_yticks(range(len(problem_ids)))
    ax.set_yticklabels(problem_ids)
    ax.set_xlabel('Pass Rate')
    ax.set_title('Top 20 Problems by Pass Rate')
    ax.grid(True, alpha=0.3, axis='x')
    
    ax = axes[1]
    sorted_problems = sorted(problem_analysis.items(), key=lambda x: x[1]["best_speedup"], reverse=True)[:20]
    problem_ids = [p[0][:25] for p in sorted_problems]
    speedups = [p[1]["best_speedup"] for p in sorted_problems]
    ax.barh(range(len(problem_ids)), speedups, color='green')
    ax.set_yticks(range(len(problem_ids)))
    ax.set_yticklabels(problem_ids)
    ax.set_xlabel('Best Speedup')
    ax.set_title('Top 20 Problems by Best Speedup')
    ax.axvline(x=1.0, color='red', linestyle='--', linewidth=2)
    ax.grid(True, alpha=0.3, axis='x')
    
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'problem_rankings.png'), dpi=150)
    plt.close()
    
    fig, ax = plt.subplots(figsize=(10, 6))
    pass_at_1 = [p["pass_at_1"] for p in problem_analysis.values()]
    pass_at_5 = [p["pass_at_5"] for p in problem_analysis.values()]
    pass_at_10 = [p["pass_at_10"] for p in problem_analysis.values()]
    
    data_to_plot = [pass_at_1, pass_at_5, pass_at_10]
    labels = ['Pass@1', 'Pass@5', 'Pass@10']
    
    bp = ax.boxplot(data_to_plot, labels=labels, patch_artist=True)
    colors = ['lightblue', 'lightgreen', 'lightyellow']
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color)
    
    ax.set_ylabel('Pass Rate')
    ax.set_title('Distribution of Pass@K Across Problems')
    ax.grid(True, alpha=0.3, axis='y')
    plt.savefig(os.path.join(output_dir, 'pass_at_k_boxplot.png'), dpi=150)
    plt.close()
    
    logger.info("Plots saved to %s", output_dir)


def generate_report(data: dict[str, Any], output_dir: str) -> str:
    """Generate a detailed text report."""
    problem_analysis = analyze_by_problem(data)
    turn_analysis = analyze_by_turn(data)
    speedup_dist = analyze_speedup_distribution(data)
    error_patterns = analyze_error_patterns(data)
    
    total_rollouts = len(data["rollouts"])
    total_passed = sum(1 for r in data["rollouts"] if r["final_correct"])
    total_compiled = sum(1 for r in data["rollouts"] if r["final_compiled"])
    
    overall_pass_at_1 = calculate_pass_at_k(total_rollouts, total_passed, 1)
    overall_pass_at_5 = calculate_pass_at_k(total_rollouts, total_passed, 5)
    overall_pass_at_10 = calculate_pass_at_k(total_rollouts, total_passed, 10)
    
    report = []
    report.append("=" * 80)
    report.append("PASS@K EVALUATION ANALYSIS REPORT")
    report.append("=" * 80)
    report.append(f"Generated: {datetime.now().isoformat()}")
    report.append("")
    
    report.append("-" * 80)
    report.append("OVERALL SUMMARY")
    report.append("-" * 80)
    report.append(f"Total Problems: {len(problem_analysis)}")
    report.append(f"Total Rollouts: {total_rollouts}")
    report.append(f"Total Passed: {total_passed} ({total_passed/total_rollouts*100:.1f}%)")
    report.append(f"Total Compiled: {total_compiled} ({total_compiled/total_rollouts*100:.1f}%)")
    report.append("")
    report.append("Overall Pass@K Metrics:")
    report.append(f"  Pass@1: {overall_pass_at_1:.2%}")
    report.append(f"  Pass@5: {overall_pass_at_5:.2%}")
    report.append(f"  Pass@10: {overall_pass_at_10:.2%}")
    report.append("")
    
    report.append("-" * 80)
    report.append("SPEEDUP ANALYSIS")
    report.append("-" * 80)
    if "error" not in speedup_dist:
        report.append(f"Speedup Count: {speedup_dist['count']}")
        report.append(f"Min Speedup: {speedup_dist['min']:.2f}x")
        report.append(f"Max Speedup: {speedup_dist['max']:.2f}x")
        report.append(f"Mean Speedup: {speedup_dist['mean']:.2f}x")
        report.append(f"Median Speedup: {speedup_dist['median']:.2f}x")
        report.append(f"Std Dev: {speedup_dist['std']:.2f}x")
        report.append("")
        report.append("Percentiles:")
        for p, v in speedup_dist["percentiles"].items():
            report.append(f"  {p.upper()}: {v:.2f}x")
        report.append("")
        report.append("Speedup Buckets:")
        for bucket, count in speedup_dist["buckets"].items():
            report.append(f"  {bucket}: {count}")
    report.append("")
    
    report.append("-" * 80)
    report.append("TURN-BY-TURN ANALYSIS")
    report.append("-" * 80)
    for turn_key in sorted(turn_analysis.keys()):
        stats = turn_analysis[turn_key]
        report.append(f"{turn_key.replace('_', ' ').title()}:")
        report.append(f"  Total Samples: {stats['total']}")
        report.append(f"  Compile Rate: {stats['compile_rate']:.1%}")
        report.append(f"  Correct Rate: {stats['correct_rate']:.1%}")
        report.append(f"  Avg Speedup: {stats['avg_speedup']:.2f}x")
        report.append(f"  Avg Reward: {stats['avg_reward']:.2f}")
        report.append("")
    
    report.append("-" * 80)
    report.append("ERROR PATTERNS")
    report.append("-" * 80)
    report.append(f"Total Errors: {error_patterns['total_errors']}")
    for pattern, count in sorted(error_patterns['patterns'].items(), key=lambda x: -x[1]):
        report.append(f"  {pattern}: {count}")
    report.append("")
    
    report.append("-" * 80)
    report.append("TOP 10 PROBLEMS BY PASS RATE")
    report.append("-" * 80)
    sorted_by_pass = sorted(problem_analysis.items(), key=lambda x: x[1]["pass_rate"], reverse=True)[:10]
    for i, (pid, stats) in enumerate(sorted_by_pass, 1):
        report.append(f"{i}. {pid}")
        report.append(f"   Pass Rate: {stats['pass_rate']:.1%}")
        report.append(f"   Best Speedup: {stats['best_speedup']:.2f}x")
        report.append(f"   Avg Reward: {stats['avg_reward']:.2f}")
    report.append("")
    
    report.append("-" * 80)
    report.append("TOP 10 PROBLEMS BY BEST SPEEDUP")
    report.append("-" * 80)
    sorted_by_speedup = sorted(problem_analysis.items(), key=lambda x: x[1]["best_speedup"], reverse=True)[:10]
    for i, (pid, stats) in enumerate(sorted_by_speedup, 1):
        report.append(f"{i}. {pid}")
        report.append(f"   Best Speedup: {stats['best_speedup']:.2f}x")
        report.append(f"   Pass Rate: {stats['pass_rate']:.1%}")
        report.append(f"   Avg Reward: {stats['avg_reward']:.2f}")
    report.append("")
    
    report.append("=" * 80)
    
    report_text = "\n".join(report)
    
    report_path = os.path.join(output_dir, "analysis_report.txt")
    with open(report_path, "w") as f:
        f.write(report_text)
    
    logger.info("Report saved to %s", report_path)
    
    return report_text


def main():
    parser = argparse.ArgumentParser(description="Analyze PASS@K evaluation results")
    parser.add_argument("--db-path", required=True, help="Path to SQLite database")
    parser.add_argument("--output-dir", default="analysis", help="Output directory for analysis results")
    
    args = parser.parse_args()
    
    os.makedirs(args.output_dir, exist_ok=True)
    
    logger.info("Loading database from %s", args.db_path)
    data = load_database(args.db_path)
    
    logger.info("Loaded %d rollouts, %d turns, %d problem stats",
                len(data["rollouts"]), len(data["turns"]), len(data["problem_stats"]))
    
    analysis_results = {
        "by_problem": analyze_by_problem(data),
        "by_turn": analyze_by_turn(data),
        "speedup_distribution": analyze_speedup_distribution(data),
        "error_patterns": analyze_error_patterns(data),
    }
    
    analysis_path = os.path.join(args.output_dir, "analysis_results.json")
    with open(analysis_path, "w") as f:
        json.dump(analysis_results, f, indent=2, default=str)
    logger.info("Analysis results saved to %s", analysis_path)
    
    generate_plots(data, args.output_dir)
    
    report = generate_report(data, args.output_dir)
    print(report)


if __name__ == "__main__":
    main()
